---
title: "R - Logistic Regression For Credit Modelling"
output: html_notebook
---

```{r}
# Load R packages into the library

## Data management packages
library(DescTools)
library(skimr)
library(plyr)
library(dplyr)
library(aod)
library(readxl)

## Visualization packages
library(Deducer)
library(ggplot2)
library(plotly)

## Machine learnning method packages
library(ROCR)
library(pROC)
library(caret)
library(MASS)

```
```{r}
# Import dataset
# loan_data <- read.csv("loan.csv")
library(data.table)
loan_data <- fread('load_data.csv', header = T, sep = ',', data.table=FALSE)
```
```{r}
# Data management for missing observations
loan_data$mths_since_last_delinq[is.na(loan_data$mths_since_last_delinq)] <- 0
loan_data$mths_since_last_record[is.na(loan_data$mths_since_last_record)] <- 0
var.has.na <- lapply(loan_data, function(x){any(is.na(x))})
num_na <- which( var.has.na == TRUE )
per_na <- num_na/dim(loan_data)[1]
loan_data <- loan_data[complete.cases(loan_data),]
```
```{r}
# Visualization of the data
# Bar chart of the loan amount
loanamount_barchart <- ggplot(data=loan_data, aes(loan_data$loan_amnt)) + 
  geom_histogram(breaks=seq(0, 35000, by=1000), 
                 col="black", aes(fill=..count..)) +
  scale_fill_gradient("Count", low="green1", high="yellowgreen")+
  labs(title="Loan Amount", x="Amount", y="Number of Loans")
loanamount_barchart
ggplotly(p = ggplot2::last_plot())
```

```{r}
# Box plot of loan amount
box_plot_stat <- ggplot(loan_data, aes(loan_status, loan_amnt))
box_plot_stat + geom_boxplot(aes(fill = loan_status)) +
  theme(axis.text.x = element_blank()) +
  labs(list(title = "Loan amount by status", x = "Loan Status", y = "Amount"))
ggplotly(p = ggplot2::last_plot())
```

skim gives the idea about some descriptive statistics of the data as well:
```{r}
skim(loan_data)
```

```{r}
# Focus on the historical loans
loan_data=as.data.frame(loan_data[loan_data$loan_status!="Current", ])
limits_inc = quantile(loan_data$annual_inc, seq(0,1,0.1))
labels <- c(0, limits_inc[2:10], "+inf")
labels <- prettyNum(labels, big.mark = ",")
labels <- paste(labels[1:10], labels[2:11], sep = "-")
loan_data$annual_inc <- cut(loan_data$annual_inc, limits_inc, labels = labels, include.lowest = T)
loan_data[,"annual_inc"] <- as.character(loan_data[,"annual_inc"])
# Create binary variables for the logistic regression analysis
# Annual_inc
loan_data$annual_inc[loan_data$annual_inc == "70,000- 80,000"| loan_data$annual_inc == "80,000- 94,000" | loan_data$annual_inc == "94,000-120,000" | loan_data$annual_inc == "120,000-   +inf" ] <- 1
loan_data$annual_inc[loan_data$annual_inc != 1] <- 0
loan_data$annual_inc <- as.numeric(loan_data$annual_inc)
# Home_ownership
loan_data$home_ownership <- as.character(loan_data$home_ownership)
loan_data$home_ownership[loan_data$home_ownership=="OWN" | loan_data$home_ownership=="MORTGAGE"  ] <- 1       
loan_data$home_ownership[loan_data$home_ownership!=1] <- 0
# Dealinq_2yrs
loan_data$delinq_2yrs <- as.character(loan_data$delinq_2yrs)
loan_data$delinq_2yrs[loan_data$delinq_2yrs=="0"] <- 0
loan_data$delinq_2yrs[loan_data$delinq_2yrs!= 0] <- 1
# Verification status: if Verified = 1 ; otherwise = 0
loan_data$verification_status = as.character(loan_data$verification_status)
loan_data$verification_status[loan_data$verification_status == "Verified" | loan_data$verification_status == "Source Verified"] = 1
loan_data$verification_status[loan_data$verification_status != 1] = 0
loan_data$verification_status=as.numeric(loan_data$verification_status)
# Dti
dti_quant <- quantile(loan_data$dti, seq(0, 1, 0.1))
labels = c(0,prettyNum(dti_quant[2:10], big.mark = ","), "+Inf")
labels = paste(labels[1:10],labels[2:11], sep = "-")
loan_data <- mutate(loan_data, dti= cut(loan_data$dti, breaks = dti_quant, labels = factor(labels), include.lowest = T))
loan_data$dti <- as.character(loan_data$dti)
loan_data$dti[loan_data$dti == "0-6.57" | loan_data$dti == "12.13-14.32" | loan_data$dti == "14.32-16.49" ] <- 1
loan_data$dti[loan_data$dti!=1] <- 0
# Status
loan_data$loan_status <- as.character(loan_data$loan_status)
loan_data$loan_status[loan_data$loan_status == "Charged Off" | loan_data$loan_status == "Default" ] <- 1
loan_data$loan_status[loan_data$loan_status != 1] <- 0
table(loan_data$loan_status)
PercTable(loan_data$loan_status)
# Change to nummeric variables:
loan_data[,"revol_util"] <- as.numeric(sub("%", "",loan_data$"revol_util", fixed =TRUE))/100
loan_data[,"int_rate"] <- as.numeric(sub("%", "",loan_data$"int_rate", fixed =TRUE))/100
loan_data$loan_status <- as.numeric(loan_data$loan_status)
# Grouping variables
loan_data$purpose <- as.character(loan_data$purpose)
loan_data$purpose[loan_data$purpose == "car" | loan_data$purpose == "major_purchase" | 
                    loan_data$purpose == "home_improvement"| loan_data$purpose == "credit_card" ] <- 2
loan_data$purpose[loan_data$purpose == "moving" | loan_data$purpose == "small_business" | 
                    loan_data$purpose == "renewable_energy" ] <- 0
loan_data$purpose[loan_data$purpose!= 0 & loan_data$purpose!= 2 ] <- 1
loan_data$purpose <- as.factor(loan_data$purpose)
```
```{r}
##Machine Learning: Multiple  Logistic Regression Models
# Logistic: Logit stepwise Regression
logregmodI <- glm(loan_status ~ loan_amnt + home_ownership + annual_inc
            + verification_status + purpose + dti + delinq_2yrs 
            + int_rate + inq_last_6mths + mths_since_last_delinq 
            + revol_bal + revol_util + total_acc,
            data = loan_data, family = binomial(link= "logit"))
step <- stepAIC(logregmodI, direction="both")
step$anova
```
Now we need to make a training dataset and testing dataset in order to train the model and perform a ROC curve.
```{r}
# Create a training- and testing dataset
  percing <- floor((nrow(loan_data)/4)*3)       
  loan <- loan_data[sample(nrow(loan_data)), ]          
  loan.training <- loan[1:percing, ]              
  loan.testing <- loan[(percing+1):nrow(loan), ]
# Begin training of the model
  fitting.logistic <- glm(loan_status ~ loan_amnt + home_ownership + verification_status + 
                   purpose + dti + delinq_2yrs + int_rate + inq_last_6mths + 
                   mths_since_last_delinq + revol_bal + revol_util + total_acc,
                 data=loan.training,family = binomial(link= "logit"))
  summary(fitting.logistic)
```
```{r}
# AUC and ROC curve
  fitted.results <- predict(fitting.logistic, newdata = loan.testing, type = "response")
  loan.testing$prob <- fitted.results
  pred <- prediction(loan.testing$prob,loan.testing$loan_status)
  auc1 <- performance(pred, measure = "auc")
  auc1@y.values
```
```{r}
# Performance function
ROCRperf = performance(pred, "tpr", "fpr")
# Plot the ROC graph Add threshold labels 
plot(ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,by=0.1), text.adj=c(-0.2,1.7))
abline(0, 1, col= "black")
```

